### ISSUE TITLE
Consider use of type safe HTTP headers

### ISSUE THREAD

**Issue by st33v3** [zio/zio-web#25]
I've seen that you model header as two string tuple (in principle). It is far from typesafe approach. Content of header is not any string, it should be modeled  accordingly. For example, ContentLength is always long value, not a string.
I would suggest to represent each header as a separate case class. In addition to type safety, headers could be extracted in match expression or get from headers collection in safe manner.

I.e. 

```scala
case class ContentLength(length: Long) extends RawHeader
object ContentLength extends HeaderDef[ContentLength] { ... }

//later in code

request.headers match {
   case ContentLength(l) => ???
}
val cl: Option[ContentLength] = request.headers.get(ContentLength)
```
Definition of all headers would be a lot of work, but experience of HTTP ZIO users will be much better. And potential implementor may look at Akka Streams for inspiration and completeness check.

**Comment by co-category** [comment]
That header definition you are referring to is just a temporary and very early draft one just to get the ball rolling. It's not the final encoding.

**Comment by ubourdon** [comment]
Can we see a document that explain base design of the lib ?
For example have you heard about [servant](https://dev.to/bradparker/servant-s-type-level-domain-specific-language-52m8) ?

**Comment by co-category** [comment]
We are just abstracting out the models that we think will be required for now - the project is just in "warming up phase". Yeah, I know about servant and I have looked at it. I have taken some inspiration from it.

**Comment by renancaju** [comment]
Would type-safe headers prohibit the use of custom headers? If a new type `CustomHeader` is allowed, it could be used for literally anything, i.e. one could use it like `CustomHeader("Content-Length", 1000)` which would be against what one would gain from using type-safe headers.

What about validators / smart constructors that could be used only if the user judged it to be useful? For instance:

```
def asContentLength: Option[Header] = ???

`("Content-Length", 1000).asContentLength`
```

What are your thoughts?

**Comment by jypma** [comment]
I think akka-http struck a nice balance here: Headers in the RFC(s) are modelled, and custom headers can always be added, integrating into the same framework. I think that, yes, you could redefine e.g. `Content-Length` also in their model, but I don't expect that's a problem in practice, since the existing headers are easily discovered.

An interesting thing to mention is their `HttpEntity` type system, and marshalling structure, which directly integrates with certain headers (e.g. `Content-Type`, `Content-Length`, `Accept`, and others). Content-type negotiation is tough to represent in any type system, and may affect header design.

I think I agree that a base design document / mock-up code would be a good idea here, to make sure potential directions are properly covered.
