### ISSUE TITLE
Design consideration wrt middleware & composability

### ISSUE THREAD

**Issue by japgolly** [zio/zio-web#28]
Hey, so while this project is in its seeming infancy, I just raised a design issue with a similar library http4s: https://github.com/http4s/http4s/issues/3245

It might be an idea to read this and consider it now before this project grows up and the cost of change to such a consideration becomes high. Cheers & good luck

**Comment by tabdulradi** [comment]
I always find modelling routing info as a function a pain in the bum. There is no way for a middleware to reason about which endpoint did serve this request, and also makes it impossible to build reverse router which is darn useful to render templates with link to other endpoints.

I currently use @SoftwareMill's Tapir in front of http4s, which allows me to model the route info as data, then I can go through them and build my own Routing table. I wish if this project models an Endpoint as data and retain information rather than an opaque function.
